title: AJRA
description: Web Developer & Data Analyst
url: "https://ajra.es" 
baseurl: "" 

permalink: /blog/:title/

author:
  name: AJRA

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

